// src/state.js
export const state = {
  panelOpen: true,
  panelMinimized: false,
  paused: true,
  worldScale: 1.0,
  slowCooldown: 0,
  slowTimer: 0,
  slowScale: 0.35,
  slowRequested: false,
  activePreset: 'g3',
  mouseLookActive: false,
  primaryFire: false,
  jumpQueued: false,
  jumpVelocity: 0,
  jumpGrounded: true,
  pointerAimX: 0,
  pointerAimY: 0,
  keys: { w: false, a: false, s: false, d: false, space: false },
  sidebarWidth: 320,

  // Controller runtime state
  controllerConnected: false,
  controllerMoveX: 0,   // left-stick X, post-deadzone, range [-1, 1]
  controllerMoveZ: 0,   // left-stick Y, post-deadzone, range [-1, 1]

  // dash runtime
  dashTimer: 0, dashCooldown: 0,
  dashVX: 0, dashVZ: 0,
  lastMoveX: 0, lastMoveZ: 1,
  dashGhostTimer: 0,
  dashStreaks: [],

  // 3rd-person camera smooth state
  _camPos:    { x: 28, y: 28, z: 28 },
  _camTarget: { x: 0,  y: 0,  z: 0  },

  params: {
      "cameraMode": "third2",
      "isoCamD": 12,
      "thirdDist": 5,
      "thirdHeight": 3,
      "thirdFov": 62,
      "thirdMinDist": 3,
      "thirdPitchDistanceCompression": 0.75,
      "third2PitchMin": -0.9,
      "third2PitchMax": 0.85,
      "third2BodyFrameStrength": 1,
      "third2BodyFrameHeight": 1.35,
      "third2BodyScreenY": 0.45,
      "third2MinEyeHeight": 0.15,
      "thirdAzimuth": 5.028000000000173,
      "thirdLookAhead": 3.8,
      "thirdSmoothPos": 10,
      "thirdSmoothLook": 12,
      "thirdMouseLook": true,
      "thirdMouseSensitivityX": 0.003,
      "thirdMouseSensitivityY": 0.0024,
      "thirdPitch": -0.11679999999999974,
      "thirdOffsetMode": "parallel",
      "thirdOffsetX": 1.25,
      "thirdOffsetY": -0.25,
      "thirdOffsetZ": -0.25,
      "playerSpeed": 7,
      "playerColor": "#0044cc",
      "playerMetalness": 0.67,
      "playerRoughness": 0,
      "playerRadius": 0.4,
      "playerLength": 1.2,
      "playerMaxHealth": 100,
      "playerHealth": 100,
      "playerMaxArmor": 100,
      "playerArmor": 100,
      "playerInvincible": false,
      "jumpEnabled": true,
      "jumpForce": 9.5,
      "jumpGravity": 26,
      "bulletTimeEnabled": true,
      "bulletTimeDuration": 3,
      "bulletTimeCooldown": 8,
      "bulletTimeScale": 0.35,
      "shieldVisible": false,
      "shieldColor": "#1e7bff",
      "shieldOpacity": 0.22,
      "shieldRadius": 1.45,
      "shieldHexSize": 0.22,
      "shieldLineThickness": 0.012,
      "shieldGlow": true,
      "dashEnabled": true,
      "dashSpeed": 28,
      "dashDuration": 0.18,
      "dashCooldown": 1.4,
      "ambientIntensity": 0.42,
      "sunIntensity": 5.8,
      "fillIntensity": 1.35,
      "rimIntensity": 0.82,
      "sunAngleX": 16,
      "sunAngleZ": 14,
      "shadows": true,
      "shadowQuality": "high",
      "fogNear": 1,
      "fogFar": 200,
      "bgColor": "#142130",
      "floorColor": "#0C1620",
      "gridColor": "#000000",
      "showFloor": true,
      "showGrid": true,
      "showFps": true,
      "hudVisible": true,
      "hudFont": "square721TlBoldExtended",
      "reticleVisible": true,
      "reticleType": "triSpoke",
      "reticleColor": "#ffffff",
      "reticleSize": 24,
      "reticleThickness": 2,
      "reticleOpacity": 1,
      "reticleGlow": false,
      "laserEnabled": true,
      "laserBloom": true,
      "laserBloomColor": "#ff1100",
      "laserBloomIntensity": 0.55,
      "laserProjectileSpeed": 80,
      "laserRange": 42,
      "laserFireRate": 5,
      "enemyType": "rusher",
      "enemyCount": 6,
      "enemyHealth": 100,
      "enemyInvincible": false,
      "enemyBehavior": "rush",
      "enemyMoveSpeed": 2.2,
      "enemyDamage": 10,
      "enemyPlacement": "random",
      "enemyWeaponType": "contact",
      "enemyDestructionEnabled": true,
      "enemyDestructionStandardCount": 10,
      "enemyDestructionStandardSize": 0.25,
      "enemyDestructionStandardSpeed": 1,
      "enemyDestructionEliteCount": 100,
      "enemyDestructionEliteSize": 0.5,
      "enemyDestructionEliteSpeed": 1.75,
      "enemyDestructionEliteGlow": 12,

      // Controller
      "controllerEnabled": true,
      "controllerMoveDeadzone": 0.12,
      "controllerLookDeadzone": 0.10,
      "controllerLookSensX": 0.045,
      "controllerLookSensY": 0.036,
      "controllerInvertY": false,
      "controllerFireThreshold": 0.5,
      "controllerVibration": true,
  },
};

// Snapshot taken at startup — used by Reset button
export const defaultParams = JSON.parse(JSON.stringify(state.params));
