// src/state.js
export const state = {
  panelOpen: true,
  panelMinimized: false,
  paused: true,
  worldScale: 1.0,
  slowCooldown: 0,
  slowTimer: 0,
  slowScale: 0.35,
  slowRequested: false,
  activePreset: 'g19',
  mouseLookActive: false,
  isAiming: false,          // true while right-mouse / L2 held
  activeSlot: 0,            // 0 = laser, 1 = object placer
  placerRotation: 0,        // current ghost rotation in radians (multiples of π/2)
  selectedPlacedObjectIds: [],
  placerSelectionRequest: null,
  primaryFire: false,
  secondaryFire: false,       // right-click / L2 remove action while object placer is active
  jumpQueued: false,
  jumpVelocity: 0,
  jumpGrounded: true,
  jumpAirJumpsUsed: 0,
  pointerAimX: 0,
  pointerAimY: 0,
  keys: { w: false, a: false, s: false, d: false, space: false },
  sidebarWidth: 320,
  sidebarScrollTop: 0,
  explosionSplashEvents: [],

  // Controller runtime state
  controllerConnected: false,
  controllerMoveX: 0,   // left-stick X, post-deadzone, range [-1, 1]
  controllerMoveZ: 0,   // left-stick Y, post-deadzone, range [-1, 1]

  // dash runtime
  dashTimer: 0, dashCooldown: 0,
  dashVX: 0, dashVZ: 0,
  lastMoveX: 0, lastMoveZ: 1,
  dashGhostTimer: 0,
  dashStreaks: [],

  // 3rd-person camera smooth state
  _camPos:    { x: 28, y: 28, z: 28 },
  _camTarget: { x: 0,  y: 0,  z: 0  },

  params: {
      "cameraMode": "third2",
      "isoCamD": 12,
      "thirdDist": 5,
      "thirdHeight": 3,
      "thirdFov": 62,
      "thirdMinDist": 3,
      "thirdPitchDistanceCompression": 0.75,
      "third2PitchMin": -0.9,
      "third2PitchMax": 0.85,
      "third2BodyFrameStrength": 1,
      "third2BodyFrameHeight": 1.35,
      "third2BodyScreenY": 0.45,
      "third2MinEyeHeight": 0.15,
      "thirdAzimuth": 6.20092653589726,
      "thirdLookAhead": 3.8,
      "thirdSmoothPos": 10,
      "thirdSmoothLook": 12,
      "thirdMouseLook": true,
      "aimEnabled": true,
      "aimFovDelta": -18,
      "aimDistDelta": -1.5,
      "aimSpeedMult": 0.55,
      "aimSmooth": 10,
      "thirdMouseSensitivityX": 0.003,
      "thirdMouseSensitivityY": 0.0024,
      "thirdPitch": -0.19119999999999565,
      "thirdOffsetMode": "parallel",
      "thirdOffsetX": 1.25,
      "thirdOffsetY": -0.25,
      "thirdOffsetZ": -0.25,
      "cameraShakeEnabled": true,
      "cameraShakeIntensity": 1.5,
      "cameraShakeDuration": 1,
      "cameraShakeFrequency": 40,
      "cameraShakeProximity": true,
      "cameraShakeRadius": 30,
      "cameraShakeMinFactor": 0.25,
      "playerSpeed": 7,
      "playerColor": "#0044cc",
      "playerMetalness": 0.67,
      "playerRoughness": 0,
      "playerRadius": 0.4,
      "playerLength": 1.2,
      "playerMaxHealth": 100,
      "playerHealth": 0,
      "playerMaxArmor": 100,
      "playerArmor": 0,
      "playerInvincible": true,
      "jumpEnabled": true,
      "doubleJumpEnabled": true,
      "jumpForce": 9.5,
      "jumpGravity": 26,
      "bulletTimeEnabled": true,
      "bulletTimeDuration": 3,
      "bulletTimeCooldown": 8,
      "bulletTimeScale": 0.35,
      "shieldVisible": false,
      "shieldColor": "#1e7bff",
      "shieldOpacity": 0.4,
      "shieldRadius": 2.2,
      "shieldHexSize": 0.05,
      "shieldLineThickness": 0.01,
      "shieldGlow": true,
      "shieldLineBloom": 1,
      "shieldBloomIntensity": 0,
      "shieldBloomRadius": 2.01,
      "shieldFresnelPower": 3,
      "dashEnabled": true,
      "dashSpeed": 28,
      "dashDuration": 0.18,
      "dashCooldown": 1.4,
      "ambientIntensity": 0.42,
      "sunIntensity": 5.8,
      "fillIntensity": 1.35,
      "rimIntensity": 0.82,
      "sunAngleX": 16,
      "sunAngleZ": 14,
      "shadows": true,
      "shadowQuality": "high",
      "fogNear": 1,
      "fogFar": 200,
      "bgColor": "#142130",
      "floorColor": "#0C1620",
      "gridColor": "#000000",
      "showFloor": true,
      "showGrid": true,
      "showFps": true,
      "hudVisible": true,
      "hudFont": "michroma",
      "reticleVisible": true,
      "reticleType": "triSpoke",
      "reticleColor": "#ffffff",
      "reticleSize": 24,
      "reticleThickness": 2,
      "reticleOpacity": 1,
      "reticleGlow": false,
      "laserEnabled": true,
      "laserBloom": true,
      "laserBloomColor": "#ff1100",
      "laserBloomIntensity": 0.55,
      "laserProjectileSpeed": 80,
      "laserRange": 42,
      "laserFireRate": 5,
      "enemyType": "rusher",
      "enemyCount": 20,
      "enemyHealth": 10,
      "enemyInvincible": false,
      "enemyBehavior": "rush",
      "enemyMoveSpeed": 2.2,
      "enemyDamage": 10,
      "enemyPlacement": "random",
      "enemyWeaponType": "contact",
      "allyType": "sniper",
      "allyCount": 5,
      "allyHealth": 100,
      "allyInvincible": false,
      "allyBehavior": "keepDistance",
      "allyMoveSpeed": 2.2,
      "allyDamage": 10,
      "allyPlacement": "random",
      "allyWeaponType": "laser",
      "enemyDestructionEnabled": true,
      "enemyDestructionStandardCount": 10,
      "enemyDestructionStandardSize": 0.25,
      "enemyDestructionStandardSpeed": 1,
      "enemyDestructionEliteCount": 100,
      "enemyDestructionEliteSize": 0.5,
      "enemyDestructionEliteSpeed": 1.75,
      "enemyDestructionEliteGlow": 12,
      "controllerEnabled": true,
      "controllerMoveDeadzone": 0.12,
      "controllerLookDeadzone": 0.1,
      "controllerLookSensX": 0.045,
      "controllerLookSensY": 0.036,
      "controllerInvertY": false,
      "controllerFireThreshold": 0.5,
      "controllerVibration": true,
      "tagEnabled": true,
      "tagColor": "#ff2828",
      "tagSize": 25,
      "tagDwellTime": 0.6,
      "tagThickness": 12,
      "tagBloom": 0,
      "tagShadow": 1,
      "tagHeight": 30,
      "placedObjects": [
            {
                  "assetId": "cylinder",
                  "x": -9.5,
                  "y": 0.5,
                  "z": 7.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_1"
            },
            {
                  "assetId": "ramp",
                  "x": -8,
                  "y": 0,
                  "z": 4,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_2"
            },
            {
                  "assetId": "tall_box",
                  "x": -6.5,
                  "y": 1,
                  "z": 5.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_3"
            },
            {
                  "assetId": "tall_box",
                  "x": -7.5,
                  "y": 1,
                  "z": 5.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_4"
            },
            {
                  "assetId": "tall_box",
                  "x": -8.5,
                  "y": 1,
                  "z": 5.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_5"
            },
            {
                  "assetId": "tall_box",
                  "x": -9.5,
                  "y": 1,
                  "z": 5.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_6"
            },
            {
                  "assetId": "tall_box",
                  "x": -6.5,
                  "y": 1,
                  "z": 6.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_7"
            },
            {
                  "assetId": "tall_box",
                  "x": -9.5,
                  "y": 1,
                  "z": 6.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_8"
            },
            {
                  "assetId": "tall_box",
                  "x": -8.5,
                  "y": 1,
                  "z": 6.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_9"
            },
            {
                  "assetId": "tall_box",
                  "x": -7.5,
                  "y": 1,
                  "z": 6.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_a"
            },
            {
                  "assetId": "tall_box",
                  "x": -5.5,
                  "y": 1,
                  "z": 6.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_b"
            },
            {
                  "assetId": "tall_box",
                  "x": -5.5,
                  "y": 1,
                  "z": 5.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_c"
            },
            {
                  "assetId": "tall_box",
                  "x": -5.5,
                  "y": 1,
                  "z": 7.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_d"
            },
            {
                  "assetId": "tall_box",
                  "x": -6.5,
                  "y": 1,
                  "z": 7.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_e"
            },
            {
                  "assetId": "tall_box",
                  "x": -7.5,
                  "y": 1,
                  "z": 7.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_f"
            },
            {
                  "assetId": "tall_box",
                  "x": -8.5,
                  "y": 1,
                  "z": 7.5,
                  "ry": 0,
                  "scaleX": 1,
                  "scaleY": 1,
                  "scaleZ": 1,
                  "objectId": "placed_mptudxwh_g"
            }
      ],
      "placerSelectedAsset": "destructible_barrel",
      "radarEnabled": true,
      "radarRadius": 90,
      "radarRange": 60,
      "radarBgColor": "#0a1628",
      "radarEnemyColor": "#ff3030",
      "radarOpacity": 0.82,
      "radarTaggedColor": "#FF3030",
      "soundMuted": false,
      "soundMusicVolume": 0.4,
      "soundSfxVolume": 1,
      "soundSfx_shoot": 1,
      "soundSfx_dash": 1,
      "soundSfx_player_hit": 1,
      "soundSfx_standard_hit": 1,
      "soundSfx_elite_hit": 1,
      "soundSfx_explode": 1,
      "soundSfx_coin": 1,
      "soundSfx_heal": 1,
      "soundSfx_levelup": 1,
      "soundSfx_gameover": 1,
      "soundSfx_victory": 1,
      "soundSfx_ambience": 0.5,
      "enemyDestructionParticleCount": 40,
      "enemyDestructionParticleSize": 0.32,
      "enemyDestructionParticleSpeed": 1.25,
      "enemyDestructionParticleGlow": 8,
      "enemyDestructionPhysics": true,
      "destructionRusherParticleCount": 50,
      "destructionRusherParticleSize": 0.32,
      "destructionRusherParticleSpeed": 0.5,
      "destructionRusherParticleGlow": 24,
      "destructionRusherColor": "#ff0000",
      "destructionRusherPhysics": "gravity",
      "destructionRusherDespawnTime": 5,
      "destructionOrbiterParticleCount": 40,
      "destructionOrbiterParticleSize": 0.32,
      "destructionOrbiterParticleSpeed": 1.25,
      "destructionOrbiterParticleGlow": 8,
      "destructionOrbiterColor": "#00cc44",
      "destructionOrbiterPhysics": "gravity",
      "destructionOrbiterDespawnTime": 3,
      "destructionTankerParticleCount": 40,
      "destructionTankerParticleSize": 0.32,
      "destructionTankerParticleSpeed": 1.25,
      "destructionTankerParticleGlow": 8,
      "destructionTankerColor": "#2b2b2b",
      "destructionTankerPhysics": "gravity",
      "destructionTankerDespawnTime": 3,
      "destructionSniperParticleCount": 40,
      "destructionSniperParticleSize": 0.32,
      "destructionSniperParticleSpeed": 1.25,
      "destructionSniperParticleGlow": 8,
      "destructionSniperColor": "#9b30ff",
      "destructionSniperPhysics": "gravity",
      "destructionSniperDespawnTime": 3,
      "destructionTeleporterParticleCount": 40,
      "destructionTeleporterParticleSize": 0.32,
      "destructionTeleporterParticleSpeed": 1.25,
      "destructionTeleporterParticleGlow": 8,
      "destructionTeleporterColor": "#e0e0e0",
      "destructionTeleporterPhysics": "gravity",
      "destructionTeleporterDespawnTime": 3,
      "destructionShieldedParticleCount": 40,
      "destructionShieldedParticleSize": 0.32,
      "destructionShieldedParticleSpeed": 1.25,
      "destructionShieldedParticleGlow": 8,
      "destructionShieldedColor": "#4aa3ff",
      "destructionShieldedPhysics": "gravity",
      "destructionShieldedDespawnTime": 3,
      "destructionSplitterParticleCount": 100,
      "destructionSplitterParticleSize": 0.5,
      "destructionSplitterParticleSpeed": 1.75,
      "destructionSplitterParticleGlow": 12,
      "destructionSplitterColor": "#80fb37",
      "destructionSplitterPhysics": "gravity",
      "destructionSplitterDespawnTime": 3,
      "destructionBossParticleCount": 100,
      "destructionBossParticleSize": 0.5,
      "destructionBossParticleSpeed": 1.75,
      "destructionBossParticleGlow": 12,
      "destructionBossColor": "#111111",
      "destructionBossPhysics": "gravity",
      "destructionBossDespawnTime": 3,
      "destructionDestructibleParticleCount": 40,
      "destructionDestructibleParticleSize": 0.25,
      "destructionDestructibleParticleSpeed": 6,
      "destructionDestructibleParticleGlow": 8,
      "destructionDestructibleColor": "#ffffff",
      "destructionDestructiblePhysics": "gravity",
      "placerObjectColor": "#445566",
      "placerScaleX": 1,
      "placerScaleY": 1,
      "placerScaleZ": 1,
      "placerRotationDeg": 0,
      "placerTransformModalX": 22,
      "placerTransformModalY": 22,
      "soundSfx_jump": 1,
      "soundSfx_enemy_grunt": 1,
      "soundSfx_object_explode": 1,
      "destructionDestructibleShockwaveSpeed": 40,
      "destructionDestructibleShockwaveColor": "#ffffff",
      "destructionDestructibleShockwaveFadeTime": 0.12,
      "destructionDestructibleShockwaveDelay": 0,
      "destructionDestructibleShockwaveTransparency": 0.1,
      "destructionDestructibleSplashDamage": 100,
      "destructionDestructibleSplashRadius": 4,
      "destructionDestructibleSplashFalloff": 1,
      "destructionDestructibleSplashMinFactor": 0.15,
      "soundProximityEnabled": true,
      "soundProximityRange": 100,
      "soundProximityFalloff": 2,
      "soundProximityMinFactor": 0.1,
      "enemyAwarenessRange": 40,
      "allyAwarenessRange": 40
}
};

// Snapshot taken at startup — used by Reset button
export const defaultParams = JSON.parse(JSON.stringify(state.params));
